MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.2
  PRETRAIN_CKPT: "./checkpoint/MouldCTSegNet.pth"
  TRAIN_IMAGE_DIR: ".//datasets//train//Image"
  TRAIN_MASK_DIR: ".//datasets//train///Mask"
  VAL_IMAGE_DIR: './/datasets//val//Image'
  VAL_MASK_DIR: './/datasets//val//Mask'

  MODEL_DIR: './checkpoint'
  SAVE_DIR: './checkpoint'

  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 96
    DEPTHS: [ 2, 2, 2, 2 ]
    DECODER_DEPTHS: [ 2, 2, 2, 1]
    NUM_HEADS: [ 3, 6, 12, 24 ]
    WINDOW_SIZE: 7